services:
  - type: web
    name: namesilo-backend
    runtime: image
    image:
      url: pocketbase/pocketbase:latest
    startCommand: serve --http=0.0.0.0:8080
    envVars:
      - key: PB_ADMIN_EMAIL
        value: admin@namesilo.com
      - key: PB_ADMIN_PASSWORD
        value: Admin123456
